apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aoa-cluster-lab-k8s0
  namespace: gitops
spec:
  destination:
    namespace: gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/helm/app-of-apps
    repoURL: https://gitlab.k3s0.ujstor.com/clusters/customer-ujstor/utr-lab-k8s0.git
    targetRevision: main
