apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-keycloak-client-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: SecretStore
    name: "{{ .Release.Name }}-secret-store"
  target:
    name: "argocd-secret"
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        oidc.keycloak.clientSecret: "{{ `{{ .clientSecret }}` }}"
  data:
    - secretKey: oidc.keycloak.clientSecret
      remoteRef:
        key: kycloak-argo-client
        property: clientSecret
