argocd-k3s:
  argo:
    global:
      domain: argocd.utr.lab.k8s0.ujstor.dev
    server:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        extraTls:
          - hosts:
            - argocd.utr.lab.k8s0.ujstor.dev
            secretName: argocd-ingress-tls

    redis-ha:
      enabled: false
      haproxy:
        enabled: false

    configs:
      secret:
        createSecret: false
      cm:
        oidc.config: |
          name: Keycloak
          issuer: https://auth.k3s0.ujstor.com/realms/master
          clientID: argo-lab-k8s0-oauth
          clientSecret: $kycloack-argo-client:clientSecret
          requestedScopes: ["openid", "profile", "email", "groups"]
      rbac:
        policy.csv: |
          g, ArgoCDAdmins, role:admin
        scopes: "[groups]"
