apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-metallb-config-lab-k8s0
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/hook-dependency: system-metallb-operator
spec:
  destination:
    namespace: metallb
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/helm/system/metallb-config
    repoURL: https://gitlab.k3s0.ujstor.com/clusters/customer-ujstor/utr-lab-k8s0.git
    targetRevision: main
    helm:
      version: v3
      releaseName: metallb-config
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
