apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-gitlab-operator-lab-k8s0
  namespace: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  destination:
    namespace: gitlab-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/helm/system/gitlab-operator
    repoURL: https://gitlab.k3s0.ujstor.com/clusters/customer-ujstor/utr-lab-k8s0.git
    targetRevision: main
    helm:
      version: v3
      releaseName: gitlab-operator
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
