---
server:
  hosts:
    api.utr.lab.k8s0.ujstor.dev:
      api_endpoint: 
       - api.utr.lab.k8s0.ujstor.dev
      k3s_control_node: true
      k3s_server_init_node: true
  vars:
    k3s_version: v1.32.1+k3s1
    extra_server_args: >-
      --cluster-cidr=10.255.0.0/16
      --service-cidr=10.254.0.0/16
      --disable servicelb
      --disable traefik
      --flannel-backend=none
      --egress-selector-mode=disabled
      --disable-cloud-controller
      --disable-helm-controller
      --disable-network-policy
      --disable-kube-proxy
      {% for san in api_endpoint %}
      --tls-san {{ san }}
      {% endfor %}
