gitlab-k3s:
  global:
    hosts:
      domain: utr.lab.k8s0.ujstor.dev
    appConfig:
      omniauth:
        enabled: true
        allowSingleSignOn: ['openid_connect']
        blockAutoCreatedUsers: false
        autoLinkUser: ['openid_connect']
        providers:
          - secret: gitlab-lab-k8s0-oauth-secret
            key: provider
  additionalValues:
    certmanager-issuer:
      email: "astipan@mail.com"
